### ISSUE TITLE
Incompatible with grouped cms menu module

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-subsites#182] opened 2015-03-11 09:40 UTC
As Subsites module utilizes LeftAndMain_Menu.ss for showing the Subsites dropdown it overwrites the template used by https://github.com/silverstripe-australia/silverstripe-grouped-cms-menu

Is there a better way of injecting the Subsites Dropdown? How is https://github.com/sheadawson/silverstripe-userswitcher doing it? Seems it appends the form using Javascript...

**Comment by robbieaverill** [comment] 2017-07-31 05:24
Hi @wernerkrauss. We'd welcome a non-breaking pull request to make the menu more adaptable so it may work with other modules, but as this is not a bug with subsites I'm going to close it for now. Thanks!

**Closed by robbieaverill** 2017-07-31 05:24 UTC
