### ISSUE TITLE
Subsite virtual page renders without a template if pointing to an unpublished page

### ISSUE THREAD

**Issue by imprezio** [silverstripe/silverstripe-subsites#276] opened 2017-05-12 01:55 UTC
If you create a subsite virtual page, and you point it to a normal page, and the normal page is unpublished, then the subsite virtual page renders without a template.

**Comment by robbieaverill** [comment] 2017-05-12 02:00
Hi @imprezio - could you please provide your SS framework/CWP and subsites versions?

**Comment by robbieaverill** [comment] 2017-05-12 02:03
@imprezio are any of these issues related to this for you? #235 #236 #185

**Comment by robbieaverill** [comment] 2019-05-30 23:05
I can't reproduce this now using SilverStripe 4.4.x-dev with Subsites 2.3.x-dev, so closing

**Closed by robbieaverill** 2019-05-30 23:05 UTC
Labels: type/bug
