### ISSUE TITLE
"Simple" fix to make subsites multi-tab safe

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-subsites#411] opened 2019-04-29 00:41 UTC
Until #314 can be fixed fully, make subsites multi-tab safe as follows:

Refresh every "background tab" when you switch subsites in the active tab. This can likely be done through shared state (local storage) and web worker events or something. It's a stop gap measure, but a whole lot quicker to fix than making every single view and edit request in the CMS subsite aware through stateless payloads.

**Comment by NightJar** [comment] 2019-04-29 00:43
Closing as a duplicate of #314 
@chillu has just updated that issue with the same goal :)

**Comment by NightJar** [comment] 2019-04-29 00:44
Sorry, didn't see the reference in the opening there. Is the intention of this issue to split the concerns of " "fixing" the problem and providing a "stop gap" of sorts?

**Comment by sminnee** [comment] 2019-04-29 01:02
Yep so that we can track when the stop gap has been done.

**Comment by ScopeyNZ** [comment] 2019-04-29 22:28
I've dropped the impact to "high". The workaround is that you can just limit yourself to editing one subsite at a time. You can still use multiple tabs as long as they're all the same subsite. When you switch you'll have to close existing ones. It's not great by any means but it's still a workaround.

**Comment by brynwhyman** [comment] 2019-05-02 23:10
Plugging this issue here too: https://github.com/tractorcow-farm/silverstripe-fluent/issues/409

**Comment by NightJar** [comment] 2019-05-30 21:35
A simple refresh will create more problems than it solves I think. Think of the use case:

```
Background:
  I am a content editor, editing content on a page for a subsite
Given:
  I want to cross-reference some data from a different subsite
When:
  I open a new tab and switch to the subsite with that data
Then:
  I expect to be able to continue editing the content I was originally working on

But Instead:
  I have lost all my changes
```

I think the interface flow should be very similar to the functionality that exists in the CMS to "put your password back in" - the modal pop up when a CMS session times out for whatever reason.

The notice would be more along the lines of "You cannot save this content until you switch back to the `$SubsiteName` subsite on the other tab you opened". This issue is a little trickier than it seems on the surface, in that "just reloading" isn't really a good experience.

**Comment by NightJar** [comment] 2019-10-09 03:42
Enjoy: https://github.com/silverstripe/silverstripe-subsites/pull/443

**Comment by emteknetnz** [comment] 2020-07-15 21:27
Pull request still needs a fair bit of work. I'm moving this one back into the backlog so that it can get looked at afresh and re-pointed.

I've left comments on the pull-request https://github.com/silverstripe/silverstripe-subsites/pull/443#issuecomment-658709399

**Comment by emteknetnz** [comment] 2022-06-15 02:25
Closing as is essentially duplicate of https://github.com/silverstripe/silverstripe-subsites/issues/314

**Closed by emteknetnz** 2022-06-15 02:25 UTC
Labels: type/bug, affects/v4, effort/medium, impact/high
