### ISSUE TITLE
Site-selector says "Main site" while I'm on a subsite

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-subsites#164] opened 2014-10-15 13:38 UTC
The Site Selector sometimes indicates I'm on "Main Site", while, after a refresh, it's correctly indicating I'm on the subsite I was working on.

Reproduction steps:
Log on
Go to files
Upload file (Don't go "back" when done!)
Go to pages

**Comment by robbieaverill** [comment] 2017-08-01 02:34
Thanks for reporting! Closing as I can't reproduce any longer on SS 3.6.0.

**Closed by robbieaverill** 2017-08-01 02:34 UTC
