### ISSUE TITLE
UX issue when adding new page to subsite in split mode

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-subsites#355] opened 2018-04-03 02:43 UTC
When adding a new page to a subsite in split mode, after saving and/or publishing it, the preview _doesn't_ refresh, the page appears in draft mode in the site tree. Also when changing to preview mode, an error ‘The requested page could not be found’ occurs.

To recreate:
```
silverstripe/framework                    4.1.x-dev 9ed3cd4 
silverstripe/cms                          4.1.x-dev 7dea009
silverstripe/admin                        1.1.x-dev 4166209
silverstripe/asset-admin                  1.1.x-dev 4e88f38
silverstripe/errorpage                    1.1.x-dev 3b7af4c
silverstripe/versioned                    1.1.x-dev 5fe58fe

cwp/starter-theme                         dev-master 5922ad8
```

**Comment by dhensby** [comment] 2018-06-20 11:53
@brynwhyman - that's an issue not a PR, was that the right link?

**Comment by brynwhyman** [comment] 2018-06-24 22:39
@dhensby thanks - edited my comment with more detail.

**Comment by brynwhyman** [comment] 2018-07-04 23:19
Sounds like the PR for #263 has resolved this. Please confirm.

**Comment by NightJar** [comment] 2018-07-05 21:44
**When adding a new page to a subsite in split mode**
1. Load CMS on any domain (main site OK)
2. Switch to edit a subsite from the drowdown in the CMS main menu
3. Create a page using the 'Add new' button atop the site tree in the Pages section of the CMS
4. Change the title and content of this new page, click "Publish" button.


**after ~saving and/or~ publishing it**
- **the preview doesn't refresh**
- **the page appears in draft mode in the site tree.**

**Also when changing to preview mode**
1. Do not refresh the page - select "Preview" from the editing mode selection popup in the lower right

_Observe_:
- **an error ‘The requested page could not be found’ occurs.**


***

Furthermore:

1. Refresh the page (hard refresh, `(ctrl|cmd)+r`)
- Site tree now displays the page as *Modified* - although no edits have taken place since publishing.
2. Click history tab for this page
- Observe there is indeed an unpublished version exactly identical to the published version. We did not directly create this.

This latter part _may_ be caused by something in core, as a similar incident is reported with versioning in https://github.com/silverstripe/cwp/issues/118
Further investigation required to confirm/deny.

**Comment by robbieaverill** [comment] 2018-07-12 23:05
When I first create a subsite, change into it and create and save/publish a new page, I do see this problem happening.

I never see the broken preview though.

After refreshing the page I can always save and publish pages correctly in subsites with split mode enabled.

Note that PR #374 and https://github.com/silverstripe/silverstripe-fulltextsearch/pull/223 both may have been playing into causing this problem, particularly the fulltextsearch issue since it manifested itself in strange behaviour within the CMS.

I'll keep investigating the difference between a brand new and a used subsite.

**Comment by robbieaverill** [comment] 2018-07-13 03:10
I've added a Behat test that proves this bug at #378

**Comment by robbieaverill** [comment] 2018-07-13 04:05
Oh haha that test passes. It must be something in the CWP ecosystem causing this bug then.

**Comment by NightJar** [comment] 2018-07-13 04:45
My test was out of `cwp/installer`, yes. 🤔

**Comment by robbieaverill** [comment] 2018-07-18 21:52
The same issue (I think) with a screenshot: https://github.com/silverstripe/silverstripe-subsites/issues/349

**Comment by raissanorth** [comment] 2018-07-26 22:31
Using the 4.x-dev versions of framework and cms, as well as the 2.1.1 version of subsites i cannot reproduce these issues any longer. pages in the sitetree update on save _and_ publish. and the preview is rendered as expected.

**Comment by dhensby** [comment] 2018-07-30 19:56
so, "fixed in 4.3" is the conclusion? closing, then

**Comment by NightJar** [comment] 2018-07-30 20:31
>this is reproducible however

Nope, not quite @dhensby :)

The conclusion is that it's an integration issue, it (or some other component) doesn't play well with others. We've not been able to track it down yet.

**Comment by guyvanbael** [comment] 2018-10-30 15:49
seems to be happening on pages where i use colymba/gridfield-bulk-editing-tools": "dev-master

**Comment by Cheddam** [comment] 2019-05-30 23:53
I can't reproduce this using current module releases:

- `silverstripe/cms 4.3.3`
- `silverstripe/subsites 2.3.0`
- `colymba/gridfield-bulk-editing-tools 3.0.0-beta5`

@guyvanbael Are you still seeing this issue?

**Comment by guyvanbael** [comment] 2019-06-03 07:49
@Cheddam yeah, i guess it was a problem with the gridfield-bulk-editing-tools. 3.0.0-beta5 solved a lot of issues

**Comment by Cheddam** [comment] 2019-06-04 04:48
@guyvanbael Awesome, thanks for getting back to me! I'll close this out.

**Closed by Cheddam** 2019-06-04 04:48 UTC
Labels: affects/v4, effort/medium, impact/medium, type/UX, type/bug
