### ISSUE TITLE
dev/build breaks on Subsite table

### ISSUE THREAD

**Issue by Firesphere** [silverstripe/silverstripe-subsites#187] opened 2015-05-17 13:47 UTC
I get this error:
`[User Error] Couldn't run query: SELECT DISTINCT count(DISTINCT "SubsiteDomain"."ID") AS "0" FROM "SubsiteDomain" INNER JOIN "Subsite" ON "Subsite"."ID" = "SubsiteDomain"."SubsiteID" AND "Subsite"."IsPublic"=1 WHERE ('localhost:8080' LIKE replace("SubsiteDomain"."Domain",'*','%')) Table 'SubsiteDomain' doesn't exist`
It seems, Subsites database tables are created too late to work.

**Comment by robbieaverill** [comment] 2017-04-11 05:35
Discussed in person with @Firesphere - this is probably unrelated to subsites, and could possibly be caused by installing two modules at once, where the first contains a DataObject that references a DataObject from the second in its constructor. This could cause a broken reference during a dev/build. If this were the case the workaround might be to install the second module first, dev/build then install the first module.

I'm going to close this for now as it doesn't seem to have been a problem since logged.

**Closed by robbieaverill** 2017-04-11 05:35 UTC
