### ISSUE TITLE
CMS needs to be refreshed to show that a new page is published.

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-subsites#349] opened 2018-03-12 04:18 UTC
When a new page is added to a subsite, i.e. saved and published, a toast message indicates that the page is published, as expected.

However, the page still appears as a `DRAFT` in the SiteTree. Also, the `Save & Publish` button neither updates to indicate that the page is `Published` nor the correct styling is applied to it. 

![image](https://user-images.githubusercontent.com/14869519/37265520-ca7b7620-2618-11e8-842c-6294ce47e33b.png)

The correct changes are applied to the site tree and the button once the CMS is manually refreshed in the browser.

**Comment by robbieaverill** [comment] 2018-07-18 21:51
I think this is a duplicate of https://github.com/silverstripe/silverstripe-subsites/issues/355, so closing for now

**Closed by robbieaverill** 2018-07-18 21:51 UTC
Labels: affects/v4, impact/medium, type/UX, type/bug
